apiVersion: v1
kind: Service
metadata:
  namespace: utxj-workshop
  name: 230166-JosueMartinez
spec:
  selector:
    app: utxj-workshop-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
